
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 489516
 */
public class AddDialog extends javax.swing.JDialog {
    
    private EmployeeInfo newEmployee;
    private MyHashTable sharedHash;
    
    public void setSharedHash(MyHashTable hashIn) {
        sharedHash = hashIn;
    }

    /**
     * Creates new form AddDialog
     */
    public AddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        contextPanel.setVisible(false);
        cancelButton.requestFocusInWindow();
        
        numberField.setUI(new HintTextFieldUI("Employee Number",true,Color.lightGray));
        firstField.setUI(new HintTextFieldUI("First Name",true,Color.lightGray));
        lastField.setUI(new HintTextFieldUI("Last Name",true,Color.lightGray));
        deductionField.setUI(new HintTextFieldUI("Deduction Rate",true,Color.lightGray));
        
        salaryField.setUI(new HintTextFieldUI("Salary",true,Color.lightGray));
        hourlyWageField.setUI(new HintTextFieldUI("Hourly Wage",true,Color.lightGray));
        hoursPerWeekField.setUI(new HintTextFieldUI("Hours Per Week",true,Color.lightGray));
        weeksPerYearField.setUI(new HintTextFieldUI("Weeks Per Year",true,Color.lightGray));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        locationButtonGroup = new javax.swing.ButtonGroup();
        employeeTypeButtonGroup = new javax.swing.ButtonGroup();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        numberField = new javax.swing.JTextField();
        firstField = new javax.swing.JTextField();
        lastField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        genderLabel = new javax.swing.JLabel();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        mississaugaRadioButton = new javax.swing.JRadioButton();
        ottawaRadioButton = new javax.swing.JRadioButton();
        chicagoRadioButton = new javax.swing.JRadioButton();
        deductionField = new javax.swing.JTextField();
        employeeTypeLabel = new javax.swing.JLabel();
        partTimeRadioButton = new javax.swing.JRadioButton();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        contextPanel = new javax.swing.JPanel();
        partTimeContext = new javax.swing.JPanel();
        hourlyWageField = new javax.swing.JTextField();
        hoursPerWeekField = new javax.swing.JTextField();
        weeksPerYearField = new javax.swing.JTextField();
        fullTimeContext = new javax.swing.JPanel();
        salaryField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.cancelButton.text")); // NOI18N
        cancelButton.setMaximumSize(new java.awt.Dimension(75, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(75, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(75, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancelPressed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(addButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.addButton.text")); // NOI18N
        addButton.setMaximumSize(new java.awt.Dimension(75, 23));
        addButton.setMinimumSize(new java.awt.Dimension(75, 23));
        addButton.setPreferredSize(new java.awt.Dimension(75, 23));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddPressed(evt);
            }
        });

        numberField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.numberField.text")); // NOI18N
        numberField.setMinimumSize(new java.awt.Dimension(150, 20));
        numberField.setPreferredSize(new java.awt.Dimension(150, 20));

        firstField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.firstField.text")); // NOI18N
        firstField.setMinimumSize(new java.awt.Dimension(150, 20));
        firstField.setPreferredSize(new java.awt.Dimension(150, 20));

        lastField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.lastField.text")); // NOI18N
        lastField.setMinimumSize(new java.awt.Dimension(150, 20));
        lastField.setPreferredSize(new java.awt.Dimension(150, 20));

        genderButtonGroup.add(maleRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(maleRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.maleRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(genderLabel, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.genderLabel.text")); // NOI18N

        genderButtonGroup.add(femaleRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(femaleRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.femaleRadioButton.text")); // NOI18N

        genderButtonGroup.add(otherRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(otherRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.otherRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(locationLabel, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.locationLabel.text")); // NOI18N

        locationButtonGroup.add(mississaugaRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(mississaugaRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.mississaugaRadioButton.text")); // NOI18N

        locationButtonGroup.add(ottawaRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(ottawaRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.ottawaRadioButton.text")); // NOI18N

        locationButtonGroup.add(chicagoRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(chicagoRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.chicagoRadioButton.text")); // NOI18N

        deductionField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.deductionField.text")); // NOI18N
        deductionField.setMinimumSize(new java.awt.Dimension(150, 20));
        deductionField.setPreferredSize(new java.awt.Dimension(150, 20));

        org.openide.awt.Mnemonics.setLocalizedText(employeeTypeLabel, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.employeeTypeLabel.text")); // NOI18N

        employeeTypeButtonGroup.add(partTimeRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(partTimeRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.partTimeRadioButton.text")); // NOI18N
        partTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPartTimeSelected(evt);
            }
        });

        employeeTypeButtonGroup.add(fullTimeRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(fullTimeRadioButton, org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.fullTimeRadioButton.text")); // NOI18N
        fullTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFullTimeSelected(evt);
            }
        });

        contextPanel.setLayout(new java.awt.CardLayout());

        hourlyWageField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.hourlyWageField.text")); // NOI18N
        hourlyWageField.setMinimumSize(new java.awt.Dimension(150, 20));
        hourlyWageField.setPreferredSize(new java.awt.Dimension(150, 20));

        hoursPerWeekField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.hoursPerWeekField.text")); // NOI18N
        hoursPerWeekField.setMinimumSize(new java.awt.Dimension(150, 20));
        hoursPerWeekField.setPreferredSize(new java.awt.Dimension(150, 20));

        weeksPerYearField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.weeksPerYearField.text")); // NOI18N
        weeksPerYearField.setMinimumSize(new java.awt.Dimension(150, 20));
        weeksPerYearField.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout partTimeContextLayout = new javax.swing.GroupLayout(partTimeContext);
        partTimeContext.setLayout(partTimeContextLayout);
        partTimeContextLayout.setHorizontalGroup(
            partTimeContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeContextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partTimeContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        partTimeContextLayout.setVerticalGroup(
            partTimeContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        contextPanel.add(partTimeContext, "partTimeContext");

        salaryField.setText(org.openide.util.NbBundle.getMessage(AddDialog.class, "AddDialog.salaryField.text")); // NOI18N
        salaryField.setMinimumSize(new java.awt.Dimension(150, 20));
        salaryField.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout fullTimeContextLayout = new javax.swing.GroupLayout(fullTimeContext);
        fullTimeContext.setLayout(fullTimeContextLayout);
        fullTimeContextLayout.setHorizontalGroup(
            fullTimeContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullTimeContextLayout.setVerticalGroup(
            fullTimeContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        contextPanel.add(fullTimeContext, "fullTimeContext");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleRadioButton)
                            .addComponent(otherRadioButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ottawaRadioButton)
                            .addComponent(chicagoRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleRadioButton)
                            .addComponent(genderLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationLabel)
                            .addComponent(mississaugaRadioButton)))
                    .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partTimeRadioButton)
                    .addComponent(employeeTypeLabel)
                    .addComponent(fullTimeRadioButton)
                    .addComponent(contextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partTimeRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullTimeRadioButton)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(locationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioButton)
                            .addComponent(mississaugaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleRadioButton)
                            .addComponent(ottawaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherRadioButton)
                            .addComponent(chicagoRadioButton))
                        .addGap(21, 21, 21)
                        .addComponent(deductionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contextPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onCancelPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancelPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_onCancelPressed

    private void onAddPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddPressed
        // TODO add your handling code here:
        int empNum;
        try {
            empNum = Integer.valueOf(numberField.getText());
        }
        catch (NumberFormatException ex) {
            empNum = -1; // flag
        }
        
        double dedRate;
        try {
            dedRate = Double.valueOf(deductionField.getText());
        }
        catch (NumberFormatException ex) {
            dedRate = -1; // flag
        }
        
        double sal;
        try {
            sal = Double.valueOf(salaryField.getText());
        }
        catch (NumberFormatException ex) {
            sal = -1; // flag
        }
        
        double hw;
        try {
            hw = Double.valueOf(hourlyWageField.getText());
        }
        catch (NumberFormatException ex) {
            hw = -1; // flag
        }
        
        double hpw;
        try {
            hpw = Double.valueOf(hoursPerWeekField.getText());
        }
        catch (NumberFormatException ex) {
            hpw = -1; // flag
        }
        
        double wpy;
        try {
            wpy = Double.valueOf(weeksPerYearField.getText());
        }
        catch (NumberFormatException ex) {
            wpy = -1; // flag
        }
        
        if (numberField.getText().isEmpty()||firstField.getText().isEmpty()||lastField.getText().isEmpty()||deductionField.getText().isEmpty()||genderButtonGroup.getSelection()==null||locationButtonGroup.getSelection()==null||employeeTypeButtonGroup.getSelection()==null) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            
        }
        else if ((salaryField.getText().isEmpty())&&(hourlyWageField.getText().isEmpty()||hoursPerWeekField.getText().isEmpty()||weeksPerYearField.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        }
        else if (empNum <= 0) {
            JOptionPane.showMessageDialog(this, "Employee number must be a positive integer.");
        }
        else if (firstField.getText().contains("#")||lastField.getText().contains("#")) {
            JOptionPane.showMessageDialog(this, "Unsupported character '#' used in employee name."); // # is used as a delimiter in the archive file so cannot be part of names
        }
        else if (dedRate < 0 || dedRate > 1) {
            JOptionPane.showMessageDialog(this, "Deduction rate must be a decimal between 0 and 1.");
        }
        else if (sal < 0 && (hw < 0 || hpw < 0 || wpy < 0)) {
            JOptionPane.showMessageDialog(this, "Employee wage info must consist of positive numbers.");
        }
        else if (sharedHash.isInTable(empNum)) {
            JOptionPane.showMessageDialog(this, "That employee number is already in the system.");
        }
        else {
            System.out.println(sharedHash);
            // parse radio button selections for gender/location values
            int gen, loc;
            if (maleRadioButton.isSelected()) {
                gen = 0;
            }
            else if (femaleRadioButton.isSelected()) {
                gen = 1;
            }
            else {
                gen = 2;
            }
            if (mississaugaRadioButton.isSelected()) {
                loc = 0;
            }
            else if (ottawaRadioButton.isSelected()) {
                loc = 1;
            }
            else {
                loc = 2;
            }
            // call addToHash, passing in number, names, and other parameters
            if (partTimeRadioButton.isSelected()) {
                newEmployee = new PartTimeEmployee(empNum,firstField.getText(),lastField.getText(),gen,loc,dedRate,hw,hpw,wpy);
                this.dispose();
            }
            else {
                newEmployee = new FullTimeEmployee(empNum,firstField.getText(),lastField.getText(),gen,loc,dedRate,sal);
                System.out.println("full added");
                this.dispose();
            }
        }
    }//GEN-LAST:event_onAddPressed
    
    public EmployeeInfo getAddResult() {
        return newEmployee;
    }
    
    private void onPartTimeSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPartTimeSelected
        // TODO add your handling code here:
        contextPanel.setVisible(true);
        CardLayout contextCard = (CardLayout)contextPanel.getLayout();
        contextCard.show(contextPanel, "partTimeContext");
        salaryField.setText("");
    }//GEN-LAST:event_onPartTimeSelected

    private void onFullTimeSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFullTimeSelected
        // TODO add your handling code here:
        contextPanel.setVisible(true);
        CardLayout contextCard = (CardLayout)contextPanel.getLayout();
        contextCard.show(contextPanel, "fullTimeContext");
        hourlyWageField.setText("");
        hoursPerWeekField.setText("");
        weeksPerYearField.setText("");
    }//GEN-LAST:event_onFullTimeSelected
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDialog dialog = new AddDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton chicagoRadioButton;
    private javax.swing.JPanel contextPanel;
    private javax.swing.JTextField deductionField;
    private javax.swing.ButtonGroup employeeTypeButtonGroup;
    private javax.swing.JLabel employeeTypeLabel;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstField;
    private javax.swing.JPanel fullTimeContext;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JTextField lastField;
    private javax.swing.ButtonGroup locationButtonGroup;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton mississaugaRadioButton;
    private javax.swing.JTextField numberField;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JRadioButton ottawaRadioButton;
    private javax.swing.JPanel partTimeContext;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JTextField weeksPerYearField;
    // End of variables declaration//GEN-END:variables
}
