
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 489516
 */
public class EditDialog extends javax.swing.JDialog {
    
    MyHashTable sharedHash;
    int empNumToEdit;
    EmployeeInfo editedEmployee;
    EmployeeInfo removedArtifact;
    EmployeeInfo queried;

    /**
     * Creates new form EditDialog
     */
    public EditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        cancelButton.requestFocusInWindow();
        searchField.setUI(new HintTextFieldUI("Search by employee number",true,Color.lightGray));
        firstField.setUI(new HintTextFieldUI("First Name",true,Color.lightGray));
        lastField.setUI(new HintTextFieldUI("Last Name",true,Color.lightGray));
        deductionField.setUI(new HintTextFieldUI("Deduction Rate",true,Color.lightGray));
        salaryField.setUI(new HintTextFieldUI("Salary",true,Color.lightGray));
        wageField.setUI(new HintTextFieldUI("Hourly Wage",true,Color.lightGray));
        hpwField.setUI(new HintTextFieldUI("Hours Per Week",true,Color.lightGray));
        wpyField.setUI(new HintTextFieldUI("Weeks Per Year",true,Color.lightGray));
        CardLayout contextCard = (CardLayout)contextPanel.getLayout();
        contextCard.show(contextPanel, "hintErrorPanel");
        typeContextPanel.setVisible(false);
        doneButton.setEnabled(false);
    }
    
    public void setSharedHash(MyHashTable hashIn) {
        sharedHash = hashIn;
    }
    
    public void autoSearch(int empNumArg) {
        searchField.setText(String.valueOf(empNumArg));
        searchButton.doClick();
    }
    
    public EmployeeInfo[] getEditResult() {
        EmployeeInfo arr[] = {removedArtifact, editedEmployee};
        return arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        locationButtonGroup = new javax.swing.ButtonGroup();
        typeButtonGroup = new javax.swing.ButtonGroup();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        contextPanel = new javax.swing.JPanel();
        hintErrorPanel = new javax.swing.JPanel();
        hintErrorText = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        firstField = new javax.swing.JTextField();
        lastField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        genderLabel = new javax.swing.JLabel();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        mississaugaRadioButton = new javax.swing.JRadioButton();
        ottawaRadioButton = new javax.swing.JRadioButton();
        chicagoRadioButton = new javax.swing.JRadioButton();
        deductionField = new javax.swing.JTextField();
        employeeTypeLabel = new javax.swing.JLabel();
        partTimeRadioButton = new javax.swing.JRadioButton();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        typeContextPanel = new javax.swing.JPanel();
        fullContext = new javax.swing.JPanel();
        salaryField = new javax.swing.JTextField();
        partContext = new javax.swing.JPanel();
        wageField = new javax.swing.JTextField();
        hpwField = new javax.swing.JTextField();
        wpyField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.title")); // NOI18N

        searchField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.searchField.text")); // NOI18N
        searchField.setMinimumSize(new java.awt.Dimension(295, 20));
        searchField.setPreferredSize(new java.awt.Dimension(295, 20));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldonTextFieldEnter(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(searchButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.searchButton.text")); // NOI18N
        searchButton.setMaximumSize(new java.awt.Dimension(75, 23));
        searchButton.setMinimumSize(new java.awt.Dimension(75, 23));
        searchButton.setPreferredSize(new java.awt.Dimension(75, 23));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtononSearchPressed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.cancelButton.text")); // NOI18N
        cancelButton.setMaximumSize(new java.awt.Dimension(75, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(75, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(75, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtononCancelPressed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(doneButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.doneButton.text")); // NOI18N
        doneButton.setMaximumSize(new java.awt.Dimension(75, 23));
        doneButton.setMinimumSize(new java.awt.Dimension(75, 23));
        doneButton.setPreferredSize(new java.awt.Dimension(75, 23));
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDonePressed(evt);
            }
        });

        contextPanel.setPreferredSize(new java.awt.Dimension(100, 210));
        contextPanel.setLayout(new java.awt.CardLayout());

        hintErrorPanel.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hintErrorText, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.hintErrorText.text")); // NOI18N

        javax.swing.GroupLayout hintErrorPanelLayout = new javax.swing.GroupLayout(hintErrorPanel);
        hintErrorPanel.setLayout(hintErrorPanelLayout);
        hintErrorPanelLayout.setHorizontalGroup(
            hintErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hintErrorPanelLayout.createSequentialGroup()
                .addComponent(hintErrorText)
                .addGap(0, 156, Short.MAX_VALUE))
        );
        hintErrorPanelLayout.setVerticalGroup(
            hintErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hintErrorPanelLayout.createSequentialGroup()
                .addComponent(hintErrorText)
                .addGap(0, 196, Short.MAX_VALUE))
        );

        contextPanel.add(hintErrorPanel, "hintErrorPanel");

        firstField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.firstField.text")); // NOI18N
        firstField.setMinimumSize(new java.awt.Dimension(150, 20));
        firstField.setPreferredSize(new java.awt.Dimension(150, 20));

        lastField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.lastField.text")); // NOI18N
        lastField.setMinimumSize(new java.awt.Dimension(150, 20));
        lastField.setPreferredSize(new java.awt.Dimension(150, 20));

        genderButtonGroup.add(maleRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(maleRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.maleRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(genderLabel, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.genderLabel.text")); // NOI18N

        genderButtonGroup.add(femaleRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(femaleRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.femaleRadioButton.text")); // NOI18N

        genderButtonGroup.add(otherRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(otherRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.otherRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(locationLabel, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.locationLabel.text")); // NOI18N

        locationButtonGroup.add(mississaugaRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(mississaugaRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.mississaugaRadioButton.text")); // NOI18N

        locationButtonGroup.add(ottawaRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(ottawaRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.ottawaRadioButton.text")); // NOI18N

        locationButtonGroup.add(chicagoRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(chicagoRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.chicagoRadioButton.text")); // NOI18N

        deductionField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.deductionField.text")); // NOI18N
        deductionField.setMinimumSize(new java.awt.Dimension(150, 20));
        deductionField.setPreferredSize(new java.awt.Dimension(150, 20));

        org.openide.awt.Mnemonics.setLocalizedText(employeeTypeLabel, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.employeeTypeLabel.text")); // NOI18N

        typeButtonGroup.add(partTimeRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(partTimeRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.partTimeRadioButton.text")); // NOI18N
        partTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPartTimeSelected(evt);
            }
        });

        typeButtonGroup.add(fullTimeRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(fullTimeRadioButton, org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.fullTimeRadioButton.text")); // NOI18N
        fullTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFullTimeSelected(evt);
            }
        });

        typeContextPanel.setLayout(new java.awt.CardLayout());

        salaryField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.salaryField.text")); // NOI18N
        salaryField.setMinimumSize(new java.awt.Dimension(150, 20));
        salaryField.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout fullContextLayout = new javax.swing.GroupLayout(fullContext);
        fullContext.setLayout(fullContextLayout);
        fullContextLayout.setHorizontalGroup(
            fullContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullContextLayout.setVerticalGroup(
            fullContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        typeContextPanel.add(fullContext, "fullContext");

        wageField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.wageField.text")); // NOI18N
        wageField.setMinimumSize(new java.awt.Dimension(150, 20));
        wageField.setPreferredSize(new java.awt.Dimension(150, 20));

        hpwField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.hpwField.text")); // NOI18N
        hpwField.setMinimumSize(new java.awt.Dimension(150, 20));
        hpwField.setPreferredSize(new java.awt.Dimension(150, 20));

        wpyField.setText(org.openide.util.NbBundle.getMessage(EditDialog.class, "EditDialog.wpyField.text")); // NOI18N
        wpyField.setMinimumSize(new java.awt.Dimension(150, 20));
        wpyField.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout partContextLayout = new javax.swing.GroupLayout(partContext);
        partContext.setLayout(partContextLayout);
        partContextLayout.setHorizontalGroup(
            partContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partContextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wpyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        partContextLayout.setVerticalGroup(
            partContextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partContextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hpwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wpyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        typeContextPanel.add(partContext, "partContext");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addGap(36, 36, 36)
                        .addComponent(locationLabel))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleRadioButton)
                            .addComponent(femaleRadioButton)
                            .addComponent(otherRadioButton))
                        .addGap(12, 12, 12)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ottawaRadioButton)
                            .addComponent(mississaugaRadioButton)
                            .addComponent(chicagoRadioButton)))
                    .addComponent(deductionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeTypeLabel)
                    .addComponent(partTimeRadioButton)
                    .addComponent(fullTimeRadioButton))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPanelLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(typeContextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationLabel)
                            .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioButton)
                            .addComponent(mississaugaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleRadioButton)
                            .addComponent(ottawaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherRadioButton)
                            .addComponent(chicagoRadioButton)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(employeeTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partTimeRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullTimeRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deductionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPanelLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(typeContextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        contextPanel.add(editPanel, "editPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contextPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldonTextFieldEnter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldonTextFieldEnter
        // TODO add your handling code here:
        searchButton.doClick();
    }//GEN-LAST:event_searchFieldonTextFieldEnter

    private void searchButtononSearchPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtononSearchPressed
        // TODO add your handling code here:
        // if num in hash, switch card layout to confirmation label
        CardLayout contextCard = (CardLayout)contextPanel.getLayout();
        try {
            empNumToEdit = Integer.valueOf(searchField.getText());
        }
        catch (NumberFormatException ex) {
            empNumToEdit = -1;
        }
        if (empNumToEdit > 0) {
            if (sharedHash.isInTable(empNumToEdit)) {
                contextCard.show(contextPanel, "editPanel");
                queried = sharedHash.readFromTable(empNumToEdit);

                firstField.setText(queried.firstName);
                lastField.setText(queried.lastName);
                deductionField.setText(String.valueOf(queried.deductionsRate));

                if (queried.gender == 0) {
                    genderButtonGroup.setSelected(maleRadioButton.getModel(),true);
                }
                else if (queried.gender == 1) {
                    genderButtonGroup.setSelected(femaleRadioButton.getModel(),true);
                }
                else {
                    genderButtonGroup.setSelected(otherRadioButton.getModel(),true);
                }

                if (queried.workLocation == 0) {
                    locationButtonGroup.setSelected(mississaugaRadioButton.getModel(),true);
                }
                else if (queried.workLocation == 1) {
                    locationButtonGroup.setSelected(ottawaRadioButton.getModel(),true);
                }
                else {
                    locationButtonGroup.setSelected(chicagoRadioButton.getModel(),true);
                }

                if (queried instanceof PartTimeEmployee) {
                    typeButtonGroup.setSelected(partTimeRadioButton.getModel(), true);
                    CardLayout typeContextCard = (CardLayout)typeContextPanel.getLayout();
                    typeContextCard.show(typeContextPanel, "partContext");
                    typeContextPanel.setVisible(true);
                    salaryField.setText(null);
                    wageField.setText(String.valueOf(((PartTimeEmployee)queried).hourlyWage));
                    hpwField.setText(String.valueOf(((PartTimeEmployee)queried).hoursPerWeek));
                    wpyField.setText(String.valueOf(((PartTimeEmployee)queried).weeksPerYear));
                }
                else {
                    typeButtonGroup.setSelected(fullTimeRadioButton.getModel(),true);
                    CardLayout typeContextCard = (CardLayout)typeContextPanel.getLayout();
                    typeContextCard.show(typeContextPanel, "fullContext");
                    typeContextPanel.setVisible(true);
                    salaryField.setText(String.valueOf(((FullTimeEmployee)queried).salary));
                    wageField.setText(null);
                    hpwField.setText(null);
                    wpyField.setText(null);
                }
                doneButton.setEnabled(true);
            }
            else {
                contextCard.show(contextPanel, "hintErrorPanel");
                hintErrorText.setText("No such employee found in the system.");
                doneButton.setEnabled(false);

            }
        }
        else {
            contextCard.show(contextPanel, "hintErrorPanel");
            hintErrorText.setText("No such employee found in the system.");
            doneButton.setEnabled(false);
        }
    }//GEN-LAST:event_searchButtononSearchPressed

    private void cancelButtononCancelPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtononCancelPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtononCancelPressed

    private void onPartTimeSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPartTimeSelected
        // TODO add your handling code here:
        typeContextPanel.setVisible(true);
        CardLayout typeContextCard = (CardLayout)typeContextPanel.getLayout();
        typeContextCard.show(typeContextPanel, "partContext");
        salaryField.setText(null);
    }//GEN-LAST:event_onPartTimeSelected

    private void onFullTimeSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFullTimeSelected
        // TODO add your handling code here:
        typeContextPanel.setVisible(true);
        CardLayout typeContextCard = (CardLayout)typeContextPanel.getLayout();
        typeContextCard.show(typeContextPanel, "fullContext");
        wageField.setText(null);
        hpwField.setText(null);
        wpyField.setText(null);
    }//GEN-LAST:event_onFullTimeSelected

    private void onDonePressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDonePressed
        // TODO add your handling code here:
        /*int empNum;
        try {
            empNum = Integer.valueOf(searchField.getText());
        }
        catch (NumberFormatException ex) {
            empNum = -1; // flag
        }*/
        int empNum = queried.getEmpNum();
        
        double dedRate;
        try {
            dedRate = Double.valueOf(deductionField.getText());
        }
        catch (NumberFormatException ex) {
            dedRate = -1; // flag
        }
        
        double sal;
        try {
            sal = Double.valueOf(salaryField.getText());
        }
        catch (NumberFormatException ex) {
            sal = -1; // flag
        }
        
        double hw;
        try {
            hw = Double.valueOf(wageField.getText());
        }
        catch (NumberFormatException ex) {
            hw = -1; // flag
        }
        
        double hpw;
        try {
            hpw = Double.valueOf(hpwField.getText());
        }
        catch (NumberFormatException ex) {
            hpw = -1; // flag
        }
        
        double wpy;
        try {
            wpy = Double.valueOf(wpyField.getText());
        }
        catch (NumberFormatException ex) {
            wpy = -1; // flag
        }
        
        if (searchField.getText().isEmpty()||firstField.getText().isEmpty()||lastField.getText().isEmpty()||deductionField.getText().isEmpty()||genderButtonGroup.getSelection()==null||locationButtonGroup.getSelection()==null||typeButtonGroup.getSelection()==null) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            
        }
        else if ((salaryField.getText().isEmpty())&&(wageField.getText().isEmpty()||hpwField.getText().isEmpty()||wpyField.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        }
        else if (empNum <= 0) {
            JOptionPane.showMessageDialog(this, "Employee number must be a positive integer.");
        }
        else if (firstField.getText().contains("#")||lastField.getText().contains("#")) {
            JOptionPane.showMessageDialog(this, "Unsupported character '#' used in employee name."); // # is used as a delimiter in the archive file so cannot be part of names
        }
        else if (dedRate < 0 || dedRate > 1) {
            JOptionPane.showMessageDialog(this, "Deduction rate must be a decimal between 0 and 1.");
        }
        else if (sal < 0 && (hw < 0 || hpw < 0 || wpy < 0)) {
            JOptionPane.showMessageDialog(this, "Employee wage info must consist of positive numbers.");
        }
        //else if (queried != sharedHash.readFromTable(empNum)) {
        //    JOptionPane.showMessageDialog(this, "Error: Contents of search field no longer match query. Please search again.");
        //}
        else {
            // parse radio button selections for gender/location values
            int gen, loc;
            if (maleRadioButton.isSelected()) {
                gen = 0;
            }
            else if (femaleRadioButton.isSelected()) {
                gen = 1;
            }
            else {
                gen = 2;
            }
            if (mississaugaRadioButton.isSelected()) {
                loc = 0;
            }
            else if (ottawaRadioButton.isSelected()) {
                loc = 1;
            }
            else {
                loc = 2;
            }
            // call addToHash, passing in number, names, and other parameters
            removedArtifact = sharedHash.readFromTable(empNum);
            if (partTimeRadioButton.isSelected()) {
                editedEmployee = new PartTimeEmployee(empNum,firstField.getText(),lastField.getText(),gen,loc,dedRate,hw,hpw,wpy);
                this.dispose();
            }
            else {
                editedEmployee = new FullTimeEmployee(empNum,firstField.getText(),lastField.getText(),gen,loc,dedRate,sal);
                this.dispose();
            }
        }
    }//GEN-LAST:event_onDonePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditDialog dialog = new EditDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton chicagoRadioButton;
    private javax.swing.JPanel contextPanel;
    private javax.swing.JPanel contextPanel1;
    private javax.swing.JPanel contextPanel2;
    private javax.swing.JTextField deductionField;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JLabel employeeTypeLabel;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstField;
    private javax.swing.JPanel fullContext;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel hintErrorPanel;
    private javax.swing.JLabel hintErrorText;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JTextField hourlyWageField1;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JTextField hoursPerWeekField1;
    private javax.swing.JTextField hpwField;
    private javax.swing.JTextField lastField;
    private javax.swing.ButtonGroup locationButtonGroup;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton mississaugaRadioButton;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JRadioButton ottawaRadioButton;
    private javax.swing.JPanel partContext;
    private javax.swing.JPanel partTimeContext;
    private javax.swing.JPanel partTimeContext1;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JPanel typeContextPanel;
    private javax.swing.JTextField wageField;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JTextField weeksPerYearField1;
    private javax.swing.JTextField wpyField;
    // End of variables declaration//GEN-END:variables
}
